config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :slideshows do
      resources :slides do
        collection do
          post :update_positions
        end
      end
    end
    
    resource :slide_settings
  end

end

app/models/slideshow_type.rb
class SlideshowType < ActiveRecord::Base
  has_many :slides
  after_update :reprocess_slides
  
  attr_accessible :category, :slide_width, :slide_height, :slide_number, :enable_navigation, :enabled, :enable_pagination
  
  validates :slide_number, :slide_width, :slide_height, :presence => true
  validates_uniqueness_of :category
  validates_numericality_of :slide_number, :only_integer => true
  
  scope :enable, where("enabled IS NOT NULL AND enabled = 1")
  
  def reprocess_slides
    self.slides.each do |slide|
      slide.attachment_width = self.slide_width
      slide.attachment_height = self.slide_height
      slide.save!
      slide.attachment.reprocess!(:custom)
    end
  end
end

app/models/spree/slideshow.rb
module Spree
  class Slideshow < ActiveRecord::Base
    has_many :slides, :dependent => :destroy, :order => "position ASC"
    
    validates :category, :presence => true
    validates_uniqueness_of :category

    scope :enable, lambda { |category| {:conditions => {:enabled => true, :category => category}} }
    
    def mode_enum
      [[I18n.t(:horizontal), "horizontal"], [I18n.t(:fade), "fade"], [I18n.t(:vertical), "vertical"]]
    end
  end
end

app/models/spree/slideshow_type.rb
module Spree
  class SlideshowType < ActiveRecord::Base
    has_many :slides, :dependent => :destroy
    
    attr_accessible :category, :enable_navigation, :enabled, :enable_pagination
    
    validates :category, :presence => true
    validates_uniqueness_of :category
    
    scope :enable, lambda { |category| {:conditions => {:enabled => true, :category => category}} }
  end
end

app/controllers/spree/admin/slideshows_controller.rb
module Spree
  module Admin
    class SlideshowsController < ResourceController
      def index
        respond_with(@collection)
      end
      
      def show
        redirect_to( :action => :edit )
      end
      
      protected
      def find_resource
        Spree::Slideshow.find(params[:id])
      end
      
      def location_after_save
         edit_admin_slideshow_url(@slideshow)
      end
      
      def collection
        return @collection if @collection.present?
        params[:q] ||= {}
        params[:q][:s] ||= "category asc"
        
        @search = super.ransack(params[:q])
        @collection = @search.result
      end
    end
  end 
end

app/helpers/spree/slideshows_helper.rb
# encoding: UTF-8
module Spree
  module SlideshowsHelper
    
    def insert_slideshow(params={})
      params[:id] ||= "slideshow"
      params[:class] ||= "first_slideshow"
      params[:category] ||= "home"
      params[:auto] ||= false
      params[:next_text] ||= '>>'
      params[:prev_text] ||= '<<'
      params[:next_selector] ||= 'bx-next'
      params[:prev_selector] ||= 'bx-prev'
      @@slideshow = Spree::Slideshow.enable(params[:category]).try(:first)
      if @@slideshow.blank? || (!@@slideshow.blank? && @@slideshow.slides.enable.empty?)
        return ''
      end
      params[:pagination_class] ||= ""
      res = []
      
      res << content_tag(:ul, slide_images(params, @@slideshow), :class => "bxslider #{params[:class]}", :id => params[:id])
      res << "<script type='text/javascript'>
        $(function() {
          $('##{params[:id]}').bxSlider({
            auto: #{params[:auto]},
            adaptiveHeight: true,
            autoStart: #{@@slideshow.auto_start},
            mode: '#{@@slideshow.mode}',
            controls: #{@@slideshow.enable_navigation},
            nextText: '#{params[:next_text]}',
            nextSelector: '#{params[:next_selector]}',
            prevText: '#{params[:prev_text]}',
            prevSelector: '#{params[:prev_selector]}',
            speed: 2000,
            pager: #{@@slideshow.enable_pagination},
            infiniteLoop: #{@@slideshow.infinite_loop},
            hideControlOnEnd: #{@@slideshow.hide_control_on_end},
            autoHover: true,
            useCSS: true,
            pagerSelector: '#{params[:pagination_class]}'
          });
        });
        </script>"
      
      res.join.html_safe
    end

    def slide_images(params, slideshow)
      params[:style] ||= "medium"
      params[:show_content] ||= false
      slides = slideshow.slides.enable.sort_by { |slide| slide.position }
      
      slides.map do |slide|
        content_tag(:li, :class => "slides") do
          divs = []
          
          divs << link_to(image_tag(slide.attachment.url(params[:style].to_sym)), (slide.url.blank? ? "javascript: void(0)" : slide.url), { :title => slide.title })
          if params[:show_content]
            divs << content_tag(:div, content_tag(:strong, raw(slide.title)) + content_tag(:p, raw(slide.presentation)), :class => "caption")
          end
          
          divs.join.html_safe
        end
      end.join.html_safe
    end
    
    def insert_carousel(params={})
      params[:id] ||= "carousel"
      params[:class] ||= "first_carousel"
      params[:category] ||= "home"
      params[:auto] ||= false
      params[:next_text] ||= '>>'
      params[:prev_text] ||= '<<'
      params[:next_selector] ||= 'bx-next'
      params[:prev_selector] ||= 'bx-prev'
      @@slideshow = Spree::Slideshow.enable(params[:category]).try(:first)
      if @@slideshow.blank? || (!@@slideshow.blank? && @@slideshow.slides.enable.empty?)
        return ''
      end
      params[:pagination_class] ||= ""
      res = []
      
      res << content_tag(:ul, carousel_images(params, @@slideshow), :class => "bxslider #{params[:class]}", :id => params[:id])
      res << "<script type='text/javascript'>
        $(function() {
          $('##{params[:id]}').bxSlider({
            auto: #{params[:auto]},
            adaptiveHeight: true,
            autoStart: #{@@slideshow.auto_start},
            mode: '#{@@slideshow.mode}',
            controls: #{@@slideshow.enable_navigation},
            nextText: '#{params[:next_text]}',
            nextSelector: '#{params[:next_selector]}',
            prevText: '#{params[:prev_text]}',
            prevSelector: '#{params[:prev_selector]}',
            speed: 2000,
            pager: #{@@slideshow.enable_pagination},
            infiniteLoop: #{@@slideshow.infinite_loop},
            hideControlOnEnd: #{@@slideshow.hide_control_on_end},
            autoHover: true,
            useCSS: true,
            pagerSelector: '#{params[:pagination_class]}'
          });
        });
        </script>"
      
      res.join.html_safe
    end
    
    def carousel_images(params, slideshow)
      params[:style] ||= "medium"
      slides = slideshow.slides.enable.sort_by { |slide| slide.position }
      
      slides.map do |slide|
        content_tag(:li, :class => "item") do
          divs = []
          
          divs << link_to(image_tag(slide.attachment.url(params[:style].to_sym)), (slide.url.blank? ? "javascript: void(0)" : slide.url), { :title => slide.title })          
          divs.join.html_safe
        end
      end.join.html_safe
    end
    
    def insert_carousel_taxon(params={})
      params[:type] ||= "bxslier"
      params[:id] ||= "carousel"
      params[:class] ||= "first_carousel"
      params[:category] ||= "home"
      params[:auto] ||= false
      params[:auto_start] ||= false
      params[:mode] ||= 'horizontal'
      params[:enable_navigation] ||= true
      params[:enable_pagination] ||= false
      params[:next_text] ||= '>>'
      params[:prev_text] ||= '<<'
      params[:next_selector] ||= 'bx-next'
      params[:prev_selector] ||= 'bx-prev'
      params[:item_width] ||= 120
      params[:item_margin] ||= 5
      @@taxon = Spree::Taxon.find_by_permalink!(params[:taxon])
      if @@taxon.blank? || (!@@taxon.blank? && @@taxon.children.empty?)
        return ''
      end
      params[:pagination_class] ||= ""
      res = []
      
      if params[:type] == "bxslider"
        res << content_tag(:ul, carousel_taxon_images(params, @@taxon), :class => "#{params[:class]}", :id => params[:id])
        res << "<script type='text/javascript'>
          $(function() {
            $('##{params[:id]}').bxSlider({
              auto: #{params[:auto]},
              adaptiveHeight: true,
              autoStart: #{params[:auto_start]},
              mode: '#{params[:mode]}',
              controls: #{params[:enable_navigation]},
              nextText: '#{params[:next_text]}',
              nextSelector: '#{params[:next_selector]}',
              prevText: '#{params[:prev_text]}',
              prevSelector: '#{params[:prev_selector]}',
              speed: 2000,
              pager: false,
              infiniteLoop: true,
              hideControlOnEnd: false,
              autoHover: true,
              useCSS: true,
              pagerSelector: '#{params[:pagination_class]}'
            });
          });
          </script>"
      else
        res << content_tag(:div, content_tag(:ul, carousel_taxon_images(params, @@taxon), :class => "slides"), :class => "#{params[:class]}", :id => params[:id])
        res << "<script type='text/javascript'>
          $(function() {
            $('##{params[:id]}').flexslider({
              itemWidth: #{params[:item_width]},
              animation: 'slide',
              animationLoop: false,
              controlNav: #{params[:enable_pagination]},
              itemMargin: #{params[:item_margin]}
            });
          });
          </script>"
      end
      
      res.join.html_safe
    end
    
    def carousel_taxon_images(params, taxon)
      items = taxon.children
      
      items.map do |item|
        content_tag(:li, :class => "item") do
          divs = []
          
          divs << link_to(image_tag(item.icon.url()), seo_url(item), { :title => item.name })
          divs.join.html_safe
        end
      end.join.html_safe
    end
    
  end
end

app/views/spree/admin/slideshows/_form.html.erb
<div data-hook="admin_slideshow_form_fields">
	<div class="left eight columns alpha" data-hook="admin_slideshow_form_left">
		<%= f.field_container :category do %>
			<%= f.label :category, t(:category) %> <span class="required">*</span><br />
			<%= f.text_field :category, :class => 'fullwidth title' %>
			<%= f.error_message_on :category %>
		<% end %>

		<%= f.field_container :enable_navigation do %>
			<%= f.label :enable_navigation, t(:enable_navigation) %><br />
			<%= f.check_box :enable_navigation %>
			<%= f.error_message_on :enable_navigation %>
		<% end %>
		
		<%= f.field_container :enable_pagination do %>
			<%= f.label :enable_pagination, t(:enable_pagination) %><br />
			<%= f.check_box :enable_pagination %>
			<%= f.error_message_on :enable_pagination %>
		<% end %>

		<%= f.field_container :enabled do %>
			<%= f.label :enabled, t(:enabled) %><br />
			<%= f.check_box :enabled %>
			<%= f.error_message_on :enabled %>
		<% end %>
	</div>
	<div class="right four columns omega" data-hook="admin_slideshow_form_right">
		<%= f.field_container :mode do %>
			<%= f.label :mode, t(:mode) %><br />
			<%= f.select(:mode, @slideshow.mode_enum, { :include_blank => false }, { :class => 'select2' }) %>
			<%= f.error_message_on :mode %>
		<% end %>

		<%= f.field_container :auto_start do %>
			<%= f.label :auto_start, t(:auto_start) %><br />
			<%= f.check_box :auto_start %>
			<%= f.error_message_on :auto_start %>
		<% end %>
		
		<%= f.field_container :infinite_loop do %>
			<%= f.label :infinite_loop, t(:infinite_loop) %><br />
			<%= f.check_box :infinite_loop %>
			<%= f.error_message_on :infinite_loop %>
		<% end %>

		<%= f.field_container :hide_control_on_end do %>
			<%= f.label :hide_control_on_end, t(:hide_control_on_end) %><br />
			<%= f.check_box :hide_control_on_end %>
			<%= f.error_message_on :hide_control_on_end %>
		<% end %>
	</div>

	<div class="clear"></div>

	<div data-hook="admin_slideshow_form_additional_fields"></div>

	<div class="clear"></div>

</div>

app/views/spree/admin/slideshows/edit.html.erb
<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_slideshows_list), admin_slideshows_url, :icon => 'icon-arrow-left' %></li>
  <li id="new_slideshow_link">
    <%= button_link_to t(:new_slideshow), new_object_url, { :remote => true, :icon => 'icon-plus', :id => 'admin_new_slideshow' } %>
  </li>
<% end %>

<%= render :partial => 'spree/admin/shared/slideshow_sub_menu' %>
<%= render :partial => 'spree/admin/shared/slideshow_tabs', :locals => { :current => 'Slideshow Details' } %>
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @slideshow } %>

<%= form_for [:admin, @slideshow], :method => :put, :html => { :multipart => true } do |f| %>
  <fieldset class="no-border-top">
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
  </fieldset>
<% end %>

app/views/spree/admin/slideshows/index.html.erb
<% content_for :page_title do %>
  <%= t(:listing_slideshows) %>
<% end %>

<% content_for :page_actions do %>
  <div class="toolbar" data-hook="toolbar">
    <ul class="actions header-action-links inline-menu">
      <li id="new_slideshow_link">
        <%= button_link_to t(:new_slideshow), new_object_url, { :remote => true, :icon => 'icon-plus', :id => 'admin_new_slideshow' } %>
      </li>
    </ul>
  </div>
<% end %>

<%= render :partial => 'spree/admin/shared/slideshow_sub_menu' %>

<div id="new_slideshow" data-hook></div>

<% if @collection.any? %>
	<table class="index" id="listing_slideshows">
		<colgroup>
		<col style="width: 55%;">
		<col style="width: 10%;">
		<col style="width: 17%;">
		</colgroup>
		<thead>
			<tr data-hook="admin_slideshows_index_headers">
				<th><%= t(:category) %></th>
				<th><%= t(:enabled) %></th>
				<th data-hook="admin_slideshows_index_header_actions" class="actions"></th>
			</tr>
		</thead>
		<tbody>
		<% @slideshows.each do |slideshow| %>
		<tr id="<%= spree_dom_id slideshow %>" data-hook="admin_slideshows_index_rows" class="<%= cycle('odd', 'even') %>">
			<td><%= slideshow.category %> (<%= slideshow.slides.count %> <%= t(:slides) %>)</td>
			<td align="center"><%= icon('icon-check icon-large') if slideshow.enabled %></td>
			<td class="actions" data-hook="admin_slideshows_index_row_actions">
				<%= link_to_edit slideshow, :no_text => true, :class => 'edit' %>
				&nbsp;
				<%= link_to_delete slideshow, :no_text => true %>
			</td>
		</tr>
		<% end %>
		</tbody>
	</table>
<% else %>
	<div class="no-objects-found">
		<%= t(:no_results) %>
	</div>
<% end %>

app/views/spree/admin/slideshows/new.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @slideshow } %>

<%= form_for [:admin, @slideshow], :html => { :multipart => true } do |f| %>

<fieldset data-hook="new_slideshow">

  <legend align="center"><%= t(:new_slideshow) %></legend>

  <%= f.field_container :category do %>
    <%= f.label :category, t(:category) %> <span class="required">*</span><br />
    <%= f.text_field :category, :class => 'fullwidth title' %>
    <%= f.error_message_on :category %>
  <% end %>

  <div data-hook="new_slideshow_attrs" class="row">

    <div class="four columns">
      <%= f.field_container :enable_navigation do %>
        <%= f.label :enable_navigation, t(:enable_navigation) %><br />
        <%= f.check_box :enable_navigation %>
		<%= f.error_message_on :enable_navigation %>
      <% end %>
    </div>
      
    <div class="four columns">
      <%= f.field_container :enable_pagination do %>
        <%= f.label :enable_pagination, t(:enable_pagination) %><br />
        <%= f.check_box :enable_pagination %>
        <%= f.error_message_on :enable_pagination %>
      <% end %>
    </div>

    <div class="four columns">
      <%= f.field_container :enabled do %>
        <%= f.label :enabled, t(:enabled) %><br />
        <%= f.check_box :enabled %>
		<%= f.error_message_on :enabled %>
      <% end %>
    </div>
	
	<div class="omega four columns">
		<%= f.field_container :auto_start do %>
			<%= f.label :auto_start, t(:auto_start) %><br />
			<%= f.check_box :auto_start %>
			<%= f.error_message_on :auto_start %>
		<% end %>
	</div>
	
	<div class="ten columns">
		<div class="three columns">
			<%= f.field_container :infinite_loop do %>
				<%= f.label :infinite_loop, t(:infinite_loop) %><br />
				<%= f.check_box :infinite_loop %>
				<%= f.error_message_on :infinite_loop %>
			<% end %>
		</div>
		
		<div class="three columns">
			<%= f.field_container :mode do %>
				<%= f.label :mode, t(:mode) %><br />
				<%= f.select(:mode, @slideshow.mode_enum, { :include_blank => false }, { :class => 'select2' }) %>
				<%= f.error_message_on :mode %>
			<% end %>
		</div>
		
		<div class="omega three columns">
			<%= f.field_container :hide_control_on_end do %>
				<%= f.label :hide_control_on_end, t(:hide_control_on_end) %><br />
				<%= f.check_box :hide_control_on_end %>
				<%= f.error_message_on :hide_control_on_end %>
			<% end %>
		</div>
	</div>
    
  </div>

  <%= render :partial => 'spree/admin/shared/new_resource_links' %>
  
</fieldset>
<% end %>

app/views/spree/admin/slideshows/new.js.erb
$("#new_slideshow").html('<%= escape_javascript(render :template => "spree/admin/slideshows/new", :formats => [:html], :handlers => [:erb]) %>');
$("#admin_new_slideshow").parent().hide();