config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :slideshows do
      resources :slides do
        collection do
          post :update_positions
        end
      end
    end
    
    resource :slide_settings
  end

end

app/views/spree/admin/shared/_slide_setting_configurations_menu.html.erb
<tr>
  <td><%= link_to t(:slide_settings), admin_slide_settings_path %></td>
  <td><%= t(:slide_settings_description) %></td>
</tr>

app/views/spree/admin/shared/_slideshow_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_slideshow_sub_tabs" class="inline-menu">
    <%= tab :slideshows, :match_path => '/slideshows' %>
    <%= tab :slide_settings, edit_admin_slide_settings_url %>
  </ul>
<% end %>

app/views/spree/admin/shared/_slideshow_tabs.html.erb
<% content_for :page_title do %>
  <%= t(:editing_slideshow) %> &ldquo;<%= @slideshow.category %>&rdquo;
<% end %>

<% content_for :sidebar_title do %>
  <span class="category"><%= @slideshow.category %></span>
<% end %>

<% content_for :sidebar do %>
  <nav class="menu">
    <ul data-hook="admin_slideshow_tabs">
      <li<%== ' class="active"' if current == 'Slideshow Details' %>>
        <%= link_to_with_icon 'icon-edit', t(:slideshow_details), edit_admin_slideshow_url(@slideshow) %>
      </li>
      <li<%== ' class="active"' if current == 'Slides' %>>
        <%= link_to_with_icon 'icon-picture', t(:slides), admin_slideshow_slides_url(@slideshow) %>
      </li>
    </ul>
  </nav>

<% end %>

app/views/spree/admin/shared/_slideshow_type_tabs.html.erb
<h1><%= t(:editing_slideshow_type) %> &ldquo;<%= @slideshow_type.category %>&rdquo;</h1>

<% content_for :sidebar do %>

  <h3><%= @slideshow_type.category %></h3>
  <br class="clear" />

  <ul class="sidebar slide-menu" data-hook="admin_slide_tabs">
    <li<%== ' class="active"' if current == 'Slideshow_type Details' %>>
      <%= link_to t(:slideshow_type_details), edit_admin_slideshow_type_url(@slideshow_type) %>
    </li>
    <li<%== ' class="active"' if current == 'Slides' %>>
      <%= link_to t(:slides), admin_slideshow_type_slides_path(@slideshow_type) %>
    </li>
  </ul>
  <br class="clear" />

<% end %>