config/routes.rb
Spree::Core::Engine.routes.draw do

  namespace :admin do
    resources :slideshows do
      resources :slides do
        collection do
          post :update_positions
        end
      end
    end
    
    resource :slide_settings
  end

end

app/models/slide.rb
class Slide < ActiveRecord::Base
  belongs_to :slideshow_type
  validate :no_attachement_errors
  attr_accessible :title, :url, :slideshow_type_id, :attachment, :attachment_width, :attachment_height
  
  has_attached_file :attachment,
            :url  => "/spree/slides/:id/:style_:basename.:extension",
            :path => ":rails_root/public/spree/slides/:id/:style_:basename.:extension",
            :styles => lambda {|a|
                {
                  :thumbnail => "100x33#",
                  :small => "300x100#",
                  :medium => "600x200#",
                  :slide => "900x300#",
                  :custom => "#{a.instance.attachment_width}x#{a.instance.attachment_height}#"
                }
            },
            :convert_options => {
                  :thumbnail => "-gravity center",
                  :small => "-gravity center",
                  :medium => "-gravity center",
                  :slide => "-gravity center",
                  :custom => "-gravity center"
            }

  validates_presence_of :slideshow_type_id
  validates_attachment_presence :attachment
  validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg', 'image/x-png', 'image/pjpeg'], :message => "deve essere JPG, JPEG, PNG o GIF"
  
  def initialize(*args)
    super(*args)
    last_slide = Slide.last
    self.position = last_slide ? last_slide.position + 1 : 0
  end

  # if there are errors from the plugin, then add a more meaningful message
  def no_attachement_errors
    unless attachment.errors.empty?
      # uncomment this to get rid of the less-than-useful interrim messages
      # errors.clear
      errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
      false
    end
  end
end

app/models/spree/slide.rb
module Spree
  class Slide < ActiveRecord::Base
    belongs_to :slideshow
    belongs_to :slideable, :polymorphic => true
    acts_as_list :scope => :slideshow
    
    validate :no_attachment_errors
    validates_presence_of :slideshow_id
    validates_attachment_presence :attachment
    validates_attachment_content_type :attachment, :content_type => ['image/jpeg', 'image/png', 'image/gif', 'image/jpg', 'image/x-png', 'image/pjpeg'], :message => I18n.t(:images_only)
        
    has_attached_file :attachment,
            :url  => "/spree/slides/:id/:style_:basename.:extension",
            :path => ":rails_root/public/spree/slides/:id/:style_:basename.:extension",
            :styles => { :mini => "60x60#", :small =>  "300x100#", :medium => "600x200#", :large =>  "900x300#"},
            convert_options: { all: '-strip -auto-orient -colorspace sRGB' }
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions
    
    default_scope order("position ASC")
    scope :enable, {:conditions => {:enabled => true}}

    include Spree::Core::S3Support
    supports_s3 :attachment

    Spree::Slide.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:slide_styles]).symbolize_keys!
    Spree::Slide.attachment_definitions[:attachment][:path] = Spree::Config[:slide_path]
    Spree::Slide.attachment_definitions[:attachment][:url] = Spree::Config[:slide_url]
    Spree::Slide.attachment_definitions[:attachment][:default_url] = Spree::Config[:slide_default_url]
    Spree::Slide.attachment_definitions[:attachment][:default_style] = Spree::Config[:slide_default_style]
    
    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end
  end
end

app/controllers/admin/slides_controller.rb
class Admin::SlidesController < Admin::ResourceController
  before_filter :load_data

  def update_positions
    params[:positions].each do |id, index|
      Slide.update_all(['position=?', index], ['id=?', id])
    end

    respond_to do |format|
      format.js  { render :text => 'Ok' }
    end
  end

  private
  def location_after_save
    admin_slideshow_type_slides_url(@slideshow_type)
  end
  
  def load_data
    @slideshow_type = SlideshowType.find(params[:slideshow_type_id])
  end
end

app/controllers/spree/admin/slides_controller.rb
module Spree
  module Admin
    class SlidesController < ResourceController
      before_filter :load_data
      
      create.before :set_slideshow
      update.before :set_slideshow
      destroy.before :destroy_before

      private
      def location_after_save
        admin_slideshow_slides_url(@slideshow)
      end
      
      def load_data
        @slideshow = Spree::Slideshow.find(params[:slideshow_id])
      end
      
      def set_slideshow
        @slide.slideshow_id = params[:slideshow_id]
      end
      
      def destroy_before
        @viewable = @slide.slideshow
      end

    end
  end
end

app/views/spree/admin/slides/_form.html.erb
<div data-hook="admin_slide_form_fields">
	<div class="eight columns alpha">
		<div data-hook="file" class="field">
			<%= f.label t(:filename) %><br>
			<%= f.file_field :attachment %>
		</div>
		<div data-hook="enabled" class="field">
			<label>
				<%= f.check_box :enabled %>
				<%= t(:enabled) %>
			</label>
		</div>
	</div>
	<div class="omega eight columns">
		<div data-hook="title" class="field">
			<%= f.label t(:title) %><br>
			<%= f.text_field :title, :class => 'fullwidth' %>
		</div>
		<div data-hook="url" class="field">
			<%= f.label t(:url) %><br>
			<%= f.text_field :url, :class => 'fullwidth' %>
		</div>
		<div data-hook="presentation" class="field">
			<%= f.label t(:presentation) %><br>
			<%= f.text_area :presentation, :rows => 4, :class => 'fullwidth' %>
		</div>
	</div>
</div>
<div class="clear"></div>

app/views/spree/admin/slides/edit.html.erb
<%= render :partial => 'spree/admin/shared/slideshow_sub_menu' %>
<%= render :partial => 'spree/admin/shared/slideshow_tabs', :locals => { :current => 'Slides' } %>

<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @slide } %>

<% content_for :page_actions do %>
  <li><%= button_link_to t(:back_to_slides_list), admin_slideshow_slides_url(@slideshow), :icon => 'icon-arrow-left' %></li>
<% end %>

<%= form_for [:admin, @slideshow, @slide], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <legend align="center"><%= @slide.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label t(:thumbnail) %><br>
      <%= link_to image_tag(@slide.attachment.url(:mini)), @slide.attachment.url(:large) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button t(:update), 'icon-refresh' %>
      <span class="or"><%= t(:or) %></span>
      <%= link_to t(:cancel), admin_slideshow_slides_url(@slideshow), :id => 'cancel_link', :class => 'button icon-remove' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/slides/index.html.erb
<%= render :partial => 'spree/admin/shared/slideshow_sub_menu' %>
<%= render :partial => 'spree/admin/shared/slideshow_tabs', :locals => {:current => 'Slides'} %>

<% content_for :page_actions do %>
  <li><%= link_to_with_icon('icon-plus', t(:new_slide), new_admin_slideshow_slide_url(@slideshow), :id => 'new_slide_link', :class => 'button') %></li>
<% end %>

<div id="slides" data-hook></div>

<% unless @slideshow.slides.any? %>
  <div class="no-objects-found">
    <%= t(:no_slides_found) %>.
  </div>
<% else %>
  <table class="index sortable" data-hook="slides_table" data-sortable-link="<%= update_positions_admin_slideshow_slides_url(@slideshow) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <col style="width: 25%">
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="slides_header">
        <th colspan="2"><%= t(:thumbnail) %></th>
        <th><%= t(:alt_text) %></th>
		<th><%= t(:enabled) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@slideshow.slides).each do |slide| %>
        <tr id="<%= spree_dom_id slide %>" data-hook="slides_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <%= link_to image_tag(slide.attachment.url(:mini)), slide.attachment.url(:large) %>
          </td>
          <td><%= slide.presentation %></td>
		  <td align="center"><%= icon('icon-check icon-large') if slide.enabled %></td>
          <td class="actions">
            <%= link_to_with_icon 'icon-edit', t(:edit), edit_admin_slideshow_slide_url(@slideshow, slide), :no_text => true, :data => {:action => 'edit'} %>
            <%= link_to_delete slide, { :url => admin_slideshow_slide_url(@slideshow, slide), :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/slides/new.html.erb
<%= form_for [:admin, @slideshow, @slide], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_image">
    <legend align="center"><%= t(:new_slide) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button t(:update), 'icon-refresh' %>
        <span class="or"><%= t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', t(:cancel), admin_slideshow_slides_url(@slideshow), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>

<%= javascript_include_tag 'admin/slides/new.js' %>